spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa735w4TghsNU2D45d5
            clieng-secret: 00pAGJnLygLJ3nPYp0fcmE4hTueVWCTK6mksL-FKW5
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-741410.okta.com/oauth2/default